### ISSUE TITLE
meta: book revamp

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/book#943]
Tracking issue for the ongoing book revamp.

### New tutorials
- [ ] Making an ERC20 with Foundry
- [ ] Deploying a proxy with Foundry
- [ ] "Your first Foundry project" — and end to end, unit/invariant/fuzz/fork & deployment tutorial.
- [ ] Migrating from Hardhat
### Outline revamp
- [ ] Move reference up to the front after guides / getting started for more visibility
- [ ] Revamp overviews to showcase features, focus on feature discoverability
- [ ] New `Testing` section decoupled from forge's outline
- [ ] Move "integrating with hardhat" into a more front-and-center position
### Misc (issues & things that don't fall in a particular category to fix, low-prio compared to above)
- #893 
- #820 
- #824 
- #789 
- #782 
- #756 
- #415 
### New outline order
- Installation
- Getting Started
- Testing
- Tutorials
  - Integrating with hardhat
- Reference
- Overviews
  - Forge
  - Cast
  - Anvil
  - Chisel
- Appendix
